version: '3'
services:
  database:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: orgchartdb
      MYSQL_USER: webapp
      MYSQL_PASSWORD: taag
    networks:
     - taag
    ports:
      - "3310:3306"
    volumes:
      - ../Back_end/Org_Chart_SQL StoredProcedure.sql:/docker-entrypoint-initdb.d/mysql-init.sql
      - mysql-data-volume:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 10s
      retries: 6
  webserver:
    image: tomcat
    environment:
      DOCKER_CHECK: 1
    depends_on:
      - database
    networks:
      - taag
    ports:
      - "8080:8080" 
    volumes:
#      - /c/wamp64/www/taag/Back_end/Taag.war:/usr/local/tomcat/webapps/Taag.war
      - /c/wamp64/www/taag/:/usr/local/tomcat/webapps/ROOT/
#      - /c/wamp64/www/taag/assets:/usr/local/tomcat/webapps/ROOT/assets
#      - /c/wamp64/www/taag/mockdata:/usr/local/tomcat/webapps/ROOT/mockdata
volumes:
  mysql-data-volume:
networks:
  taag:
