database:
  image: mysql
  environment:
    MYSQL_ROOT_PASSWORD: root
    MYSQL_DATABASE: orgchartdb
    MYSQL_USER: webapp
    MYSQL_PASSWORD: taag
  ports:
    - "3306:3306"
  volumes:
    - ../Back_end/Org_Chart_SQL StoredProcedure.sql:/docker-entrypoint-initdb.d/mysql-init.sql
webserver:
  image: tomcat
  links:
    - database:mysql 
  ports:
    - "8080:8080" 
  volumes:
    - ../Back_end/Taag/Taag.war:/usr/local/tomcat/webapps/Taag.war
    - ../index.html:/usr/local/tomcat/webapps/ROOT/index.html
    - ../assets:/usr/local/tomcat/webapps/ROOT/assets
    - ../mockdata:/usr/local/tomcat/webapps/ROOT/mockdata

