version: '3'
services:
  database:
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: orgchartdb
      MYSQL_USER: webapp
      MYSQL_PASSWORD: taag
    ports:
      - "3306:3306"
    volumes:
      - ../Back_end/Org_Chart_SQL StoredProcedure.sql:/docker-entrypoint-initdb.d/mysql-init.sql
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 10s
      retries: 6
  webserver:
    image: tomcat
    environment:
      DOCKER_CHECK: 1
    depends_on:
      - database
    links:
      - database:mysql 
    ports:
      - "8080:8080" 
    volumes:
      - ../Back_end/Taag.war:/usr/local/tomcat/webapps/Taag.war
      - ../index.html:/usr/local/tomcat/webapps/ROOT/index.html
      - ../assets:/usr/local/tomcat/webapps/ROOT/assets
      - ../mockdata:/usr/local/tomcat/webapps/ROOT/mockdata
  
